import {createSlice} from "@reduxjs/toolkit";

const initalState = {
    content:null,
    moviebookmarkdata:[],
    seriesbookmarkdata:[]
}

//creating redux slice detail with inital state and reducers
const detail = createSlice({
    name:"detail",
    initialState:initalState,
    reducers:{
        //reducer to set content in state
        setcontent:(state,action)=>{
            state.content = action.payload
        },
        //reducer to set bookmark movie data in state
        setbookmarkmoviedata : (state,action)=>{
            state.moviebookmarkdata = action.payload
        },
        //reducer to set bookmark series data in state
        setbookmarkseriesdata :(state,action)=>{
            state.seriesbookmarkdata = action.payload
        }
    }
});

//exporting the action creaters
export const {setcontent,setbookmarkmoviedata,setbookmarkseriesdata} = detail.actions;

//exporting reducer generated by detail
export default detail.reducer;